server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761/eureka/

message: Hello, I am from product service dev environment
