server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761/eureka/

message: Hello, I am from user service dev environment
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.trusted.packages: "com.example.model.event"
        spring.json.value.default.type: "com.example.model.event.BaseEvent"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      user-created: user-created
      user-updated: user-updated
      user-deleted: user-deleted
      order-created: order-created
      notifications: notifications
      dead-letter: dead-letter-topic
  retry:
    max-attempts: 3
    backoff:
      initial-interval: 1000
      multiplier: 2
      max-interval: 10000
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

logging:
  level:
    com.example.userservice: DEBUG
    org.springframework.cloud.openfeign: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
  retry:
    instances:
      productService:
        maxAttempts: 3
        waitDuration: 1000

product:
  service:
    url: http://localhost:8083/api

jwt:
  secret: mySecretKey
  expiration: 86400000
